#!/bin/bash

zscroll -l 30 \
        --delay 0.1 \
        --match-command "$1 $2" \
        --match-text "Playing" "--scroll 1" \
        --match-text "Paused" "--scroll 0" \
        --update-check true "$1" &

wait
