#!/bin/bash

# Fixes mounting windows operated partitions (ntfsfix)

device=$1
target=$(findmnt -S $device -n -o TARGET)

echo "================= Unmounting Device ==================="

sudo umount $device

echo "================ Unmounting Complete =================="

echo "================= Beginning ntfsfix ==================="

sudo ntfsfix $device

echo "==================== ntfsfix Ended ===================="

echo "================= Remounting Device ==================="

sudo mount -t ntfs-3g $device $target

echo "===================== COMPLETE ========================"
